#!/bin/sh

nasm -f bin boot.asm -o boot.bin
nasm -f bin kernel.asm -o kernel.bin

dd if=boot.bin of=os.bin bs=512 count=1
dd if=kernel.bin of=os.bin bs=512 seek=1 count=1

if [ "$1" == "v" ]; then
	./virtualize
fi
